### ISSUE TITLE
Possible Memory Leak in the JpegViewer

### ISSUE THREAD

**Issue by JeepLavoie** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI#47] opened 2023-07-03 23:34 UTC
Please, fill the following sections to help us to reproduce and fix the issue

**What happened**:

When running the GroupDoc.Viewer.UI.SelfHost in Docker and Kubernetes I saw that the instance was using a lot of memory and not release it. 

When reading the `JpegViewer.cs` in the [master branch](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/blob/master/src/GroupDocs.Viewer.UI.SelfHost.Api/Viewers/JpgViewer.cs), I saw that the `MemoryStream` declaration at the line 42 don't use the `Dispose()` or `using` pattern like Microsoft [recommend](https://learn.microsoft.com/en-us/dotnet/api/system.io.memorystream?view=net-6.0#remarks).

**What you expected to happen**:

The `MemoryStream` use in all the Viewer are dispose after they are use.

**How to reproduce it**:

- Create a new C# Web Api. 
- Follow the instruction in the project README.MD
- Use the `LocalFileStorage` without cache.
- Set the ViewerType to `ViewerType.Jpg`
- Deploy using Docker and Kubernetes
- View some heavy PDF and Word file
- Check the memory usage of the Pod, it max out quick.

**Source code sample**:

No code sample available.

**Environment**:
AKS with Ubuntu Agent.

- .NET Core version : SDK 6.0.411
- GroupDocs.Viewer.UI version : 6.0.13
- GroupDocs.Viewer.UI.SelfHost.Api version : 6.0.15
- Operative system: Last version of `mcr.microsoft.com/dotnet/aspnet:6.0` docker image.
- Others:
   - Kubernetes version 1.26.3

**Comment by vladimir-litvinchik** [comment] 2023-07-04 06:32
@JeepLavoie 

Thank you for opening this issue and sharing the details. 

@vyacheslav-prokopenko please take a look

**Comment by vyacheslav-prokopenko** [comment] 2023-07-06 08:32
Hello @JeepLavoie. It seems the problem is not with **_using_** or **_Dispose()_**. You can check official microsoft documentation 
   https://learn.microsoft.com/en-us/dotnet/api/system.io.memorystream?view=net-6.0

The Note in the middle of the article
_This type implements the IDisposable interface, but does not actually have any resources to dispose. This means that disposing it by directly calling Dispose() or by using a language construct such as using (in C#) or Using (in Visual Basic) is not necessary._

We will check additional cases further such a _InternalCaching_

Default value is 5 minutes so it can be the problem converting large files.

You can disable that 

~~~
builder.Services
    .AddControllers()
    .AddGroupDocsViewerSelfHostApi(config =>
    {
        config.ConfigureInternalCaching(options =>
        {
            options.DisableInternalCache();
        });
    })
~~~

Or change duration
~~~
builder.Services
    .AddControllers()
    .AddGroupDocsViewerSelfHostApi(config =>
    {
        config.ConfigureInternalCaching(options =>
        {
            options.SetCacheEntryExpirationTimeoutMinutes(1); 
        });
    })
~~~

And if you can provide some examples of docker/kubernetes settings it will be great so we can try to reproduce that on containerized environment

**Comment by JeepLavoie** [comment] 2023-07-07 16:29
Hello @vyacheslav-prokopenko, I had already disable the InternalCache. 

Like show in the screenshot you can see the 4 kubernetes instance that are running and their memory usage. The only code that is running in those Docker Container are the GroupDocs.Viewer.UI.

<img width="1195" alt="Screenshot 2023-07-07 at 12 15 00 PM" src="https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/assets/3975143/9851ebf2-7c09-4aef-8076-a09085220cbc">

Can you help me to diagnose the possible high memory usage.

Those are the [HelmAndDockerfile.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/11984060/HelmAndDockerfile.zip) that we used in our project.

Thanks

**Comment by vyacheslav-prokopenko** [comment] 2023-07-07 18:27
@JeepLavoie thank you for new data. I'll investigate what we can do with that

**Comment by vyacheslav-prokopenko** [comment] 2023-07-11 14:42
Hello @JeepLavoie . As I understand from screenshot that every docker instance has 1GB memory and from 500 to 800 MB memory usage. Can we get some example of incoming files sequence for GroupDocs.Viewer.UI in the containers? If it's not possible to provide examples of the files so at least just list of file type + file size? Is that some pdf (or word) files "incoming stream" or list of mixed formats?

**Comment by JeepLavoie** [comment] 2023-07-13 17:20
Hello @vyacheslav-prokopenko,

First we saw that the memory limiting was causing some issue with GroupDocs.Viewer. With 1 gb of ram with this PDF  
[SGT-Information-et-sensibilisation-1.pdf](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/12042402/SGT-Information-et-sensibilisation-1.pdf) was giving Out Of Memory Exception. So we remove all memory limit in K8s. For the generation Issue. When generating with this PDF 
[large pdf.pdf](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/12042466/large.pdf.pdf)
with can have over 1GB of memory usage for one instance.

I hope this information and those file can help you.

Thanks 😄

**Comment by CmortonDCM** [comment] 2024-01-03 16:50
@vladimir-litvinchik has there been any progress on this one? 

Thanks

**Comment by vladimir-litvinchik** [comment] 2024-01-04 07:53
@CmortonDCM 

The development team has located the issue. I'm waiting for the feedback about their plans. Will let you know as soon as I get any new information.

**Comment by denis-gvardionov** [comment] 2024-04-19 11:32
Hello @JeepLavoie !

Sorry for the delay. This issue is successfully resolved in the GroupDocs.Viewer for .NET version 24.3. Please update the GroupDocs.Viewer library in the GroupDocs.Viewer.UI project and that's all.

We improved both memory consumption and processing time while converting different PDF files to JPEG and PNG formats. You previously provided 2 sample files - "[SGT-Information-et-sensibilisation-1.pdf](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/12042402/SGT-Information-et-sensibilisation-1.pdf)" and "[large pdf.pdf](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/12042466/large.pdf.pdf)", as examples of poor performance. Here is a comparison of performance and memory consumption for these two files between old and new GroupDocs.Viewer.

"[SGT-Information-et-sensibilisation-1.pdf](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/12042402/SGT-Information-et-sensibilisation-1.pdf)", converting all 8 pages:

| GD.Viewer version | JPEG, Memory, Peak, MiB | JPEG, Memory, After cleanup, MiB | JPEG, sec | PNG, Memory, Peak, MiB | PNG, Memory, After cleanup, MiB | PNG, sec |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
| 23.3 | 1500 | 690 | 9 | 1700 | 672 | 9 |
| 24.3 | 249 | 187 | 5 | 224 | 186 | 5 |

"[large pdf.pdf](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/12042466/large.pdf.pdf)", converting all 56 pages:

| GD.Viewer version | JPEG, Memory, Peak, MiB | JPEG, Memory, After cleanup, MiB | JPEG, sec | PNG, Memory, Peak, MiB | PNG, Memory, After cleanup, MiB | PNG, sec |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
| 23.3 | 434 | 217 | 108 | 256 | 194 | 108 |
| 24.3 | 268 | 211 | 44 | 336 | 212 | 45 |

Of course, these numbers are relative to specific machine  and its specs, OS, .NET runtime, settings etc., but you can see a state of things in general.

**Closed** 2024-04-19 11:33 UTC
